language: python
python:
- 2.6
- 2.7
- 3.3
- 3.4
- 3.5
- 3.5-dev
- nightly
- pypy
- pypy3

matrix:
  fast_finish: true
  allow_failures:
    - python: nightly

install:
- pip install -e .
- pip install coveralls

script:
- coverage run --source=trueskill setup.py test

after_success:
- coveralls
