language: python
python:
- 2.7
- 3.4
- 3.5
- 3.5-dev
- 3.6
- nightly
- pypy
- pypy3

matrix:
  # Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
  include:
    - python: 3.7
      dist: xenial
      sudo: true
  fast_finish: true
  allow_failures:
    - python: nightly

install:
- pip install -e .
- pip install coveralls

script:
- coverage run --source=trueskill setup.py test

after_success:
- coveralls
